### PR TITLE
Feature/windows

### PR DESCRIPTION
**Pull request by duizendnegen**
For #14 - buildable on Windows, s3 & redis adapters removed; removed gitty library in favor of execSync.
Azure index adapter is being written; https://github.com/duizendnegen/ember-deploy-azure

### CODE REVIEW

**Comment by LevelbossMike** [comment]
Thx for starting this effort. I will move redis and s3 into addons and take a look at your azure addon asap.

**Comment by LevelbossMike** [comment]
Just as an heads-up you will need master version ember-deploy to get this to work I just pushed a fix for the custom adapter functionality.

I will most likely have the s3 and redis adapters ready as addons tomorrow so until then everything should work as expected.

**Comment by duizendnegen** [comment]
Thanks for the heads-up, I'll sync in your update.
And please be aware (as this PR already indicates) that the tests are currently broken, as it explicitly requests S3 & Redis.

**Comment by LevelbossMike** [comment]
Hi Pepijn, I just pushed the `default_adapters_addon` branch where I have removed the redis and s3 adapters from `ember-deploy`. I still need to remove gitty and update the readme but this branch should works as a sane starting point for what you want to do.

**Comment by LevelbossMike** [comment]
The necessary updates have landed on master and are published as version 0.2.0 to npm.

**Comment by duizendnegen** [comment]
Thanks - I'll close this and open a new PR for the updated code which removes the Gitty dependency.

**Comment by LevelbossMike** [comment]
Thanks! looking forward for your pr

**Pull request closed without merging**
