### PR TITLE
configure which files to gzip, defaulting to js, css & svg

### PR DESCRIPTION
**Pull request by duizendnegen**

### CODE REVIEW

**Comment by LevelbossMike** [comment]
thx!

**Comment by tylr** [comment]
@LevelbossMike @duizendnegen 

This introduces an issue with the ember-deploy-s3 extension. It is hardcoded within the uploader to expect `js` or `css` extensions. Won't have time to make a fork for a few days, but wanted to document that is happening in case anyone else is wondering why their svg's aren't displaying in browsers.

**Comment by duizendnegen** [comment]
@tylr 

thanks for the feedback. I can recommend you to update your deploy.json to include
```javascript
"gzipExtensions": ["js", "css"]
```

**Comment by LevelbossMike** [comment]
@tylr 

Thx for catching this issue.

I just fixed this in [ember-deploy-s3](https://github.com/LevelbossMike/ember-deploy-s3/commit/6b112b00d7126247f93d89414c2c02e041fcbb43) and published version 0.0.3 on npm.

`ember-deploy-s3` should now mark the files gzipped by ember-deploy as gzip content on s3. If you don't pass a gzipExtensions property in `deploy.json` the fallback is to use `ember-deploy`'s default ['js', 'css', 'svg']. 

Sorry for the inconvenience caused. Please report back any issues you are encountering.

**Pull request merged**
